title: Non-Cooperative Infinitely Repeated Games
name: Dario Gentiletti
user_description: Games, Products and Philosophy
notes_url: "https://dariogentiletti.com"
notes_description: "Notes"
profile_pic: /assets/img/profile.png
favicon: /assets/img/favicon.png
copyright_name: Dario Gentiletti
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://dariogentiletti.com" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8


# Social Media Links
twitter: https://www.twitter.com/dariogentiletti
emailid: dg3084@columbia.edu
personal_site_name: 
personal_site_url: 
linkedin: https://linkedin.com/in/dgentiletti"
github:

# Build settings
theme: null
plugins:
  - jekyll-feed 
  - jekyll-sitemap 

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

sass:
  style: compressed

collections:
    notes:
      output: true
      permalink: /notes/:title

disqus:
  shortname: dariogentiletti

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
